[package]
name = "copper_oil"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters = "0.3.7"
chrono = "0.4.43"
itertools = "0.14.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"